/** @format */

const MOMENT_DEFAULT_FORMAT = 'llll z';
const MOMENT_DB_SEARCH_FORMAT = 'YYYY-MM-DD';
const MOMENT_SHORT_DISPLAY_FORMAT = 'MMM Do YY';
export default MOMENT_DEFAULT_FORMAT;
export { MOMENT_DB_SEARCH_FORMAT, MOMENT_SHORT_DISPLAY_FORMAT };
